### ISSUE TITLE
Standing Desk Mat

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/standing-desk#23]
I've been using a _makeshift_ standing desk for a few years ... (_usually cardboard boxes on desk_)
I find that both my feet and knees suffer from prolonged standing ... 
Right now I'm standing _barefoot_ on hardwood floorboards and my feet are _feeling_ it.
(_I've been standing for around 10h today ... 3h AFK including 40mins of exercise_)

So ... I'm thinking of investing in a Standing Desk Mat: (_as this stock photo model is showing_)

![image](https://user-images.githubusercontent.com/194400/55030984-7f299180-5005-11e9-87a7-c1dd96cdfaec.png)

I want a mat that is more than just a flat piece of rubber; something with ridges and contours that I can use to occasionally flex or apply accu-pressure to specific areas of my feet ...

Comparison of mats: https://thewirecutter.com/reviews/best-standing-desk-mat
![image](https://user-images.githubusercontent.com/194400/55030715-d67b3200-5004-11e9-8f03-c18e678a4fab.png)

The Ergodriven Topo is $99 on Amazon.com:
https://www.amazon.com/Ergodriven-Not-Flat-Anti-Fatigue-Calculated-Must-Have/dp/B00V3TO9EK
![image](https://user-images.githubusercontent.com/194400/55031423-8309e380-5006-11e9-908d-253c45115e8c.png)
And sadly, for some reason it is not _available_ in the UK/EU (on Amazon)!! 😞 
It's available on Ebay: 
![image](https://user-images.githubusercontent.com/194400/55031588-d0865080-5006-11e9-87ed-ba2eefe741df.png)

But who is going to spend £130 on a piece of moulded rubber...? 😮
(_also, given that it's over £100 there will probably be import taxes to pay ..._) 🤮

Found this _rather similar_ product on ebay for 40% of the price:

https://www.ebay.co.uk/itm/Ergonomic-Anti-Fatigue-Comfort-Floor-Mat-for-Standing-Desk-Non-Slip-Not-Flat/173827521176
![image](https://user-images.githubusercontent.com/194400/55031700-088d9380-5007-11e9-80bb-ef1c37dcc41e.png)

And there are _even_ cheaper options (_for anyone reading who just wants/needs something basic_)
https://www.ebay.co.uk/itm/Anti-Fatigue-Floor-Mat-Foam-Gel-Kitchen-Rug-Office-Standing-Mat-Black-Grey/132812519269
![image](https://user-images.githubusercontent.com/194400/55031839-6b7f2a80-5007-11e9-84c3-e95aee12f7d3.png)

# Todo

+ [x] Order Standing Desk Mat
+ [ ] Test it
+ [ ] Write-up findings
+ [ ] Determine if it's worth it (_solved the problem of painful feet_) or if I need to keep searching...

**Comment by nelsonic** [comment]
Ordered the £50 one. ✅ 

![image](https://user-images.githubusercontent.com/194400/55032460-d11fe680-5008-11e9-8b41-49175418a232.png)

ETA: next week.
