### ISSUE TITLE
IKEA SIGNUM Cable Management (under desk)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/standing-desk#30]
It's a _little_ frustrating that _none_ of the IKEA desks include cable management. 🤦‍♂️ 

`SIGNUM` https://www.ikea.com/pt/en/p/signum-cable-trunking-horizontal-silver-colour-30200253/
![image](https://user-images.githubusercontent.com/194400/131111752-21a99ed3-9a15-4985-87a8-d401186f2a12.png)

Assembly instructions: requires drilling into the table top as there are no holes. seems like a fail on their part. 🙄 
https://www.ikea.com/pt/en/assembly_instructions/signum-cable-management-horizontal__AA-489805-3_pub.pdf
![image](https://user-images.githubusercontent.com/194400/131113194-955e585a-19d2-4c44-8f1d-ad3da22e9aad.png)
![image](https://user-images.githubusercontent.com/194400/131113271-385446ad-a638-4388-a049-909224c99f85.png)

# Todo

+ [ ] Buy/order the `SIGNUM`
+ [ ] Install it under the standing desk
+ [ ] De-clutter desk!
